[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn app:app"
region = "us-west2"
runtime = "V2"
numReplicas = 1
healthcheckPath = "/"
healthcheckTimeout = 100
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10